### ISSUE TITLE
Release GMT 6.0.0rc2

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1081]
**Version**:  6.0.0rc2

**Before release**:

- [x] run `src/gmt_make_*.sh` to update some .c and .h files
- [x] check if all tests pass on macOS, Linux and Windows
- [x] update changelog
- [x] update INSTALL.md
- [x] build documentations and fix warnings if any
- [x] check/set values in `cmake/ConfigDefault.cmake`
    - [x] `GMT_VERSION_YEAR` is current year
    - [x] `GMT_PACKAGE_VERSION_*` is correctly set
    - [x] `GMT_LIB_SOVERSION` is correctly set
    - [x] set `GMT_PUBLIC_RELEASE` to `TRUE`
- [x] freeze codes and commit all changes to GitHub

**Release**:

- [x] create source tarballs (tar.gz and tar.xz) (@PaulWessel)
- [x] create macOS bundle (@PaulWessel)
- [x] create Windows installers (win32 and win64) (@joa-quim)
- [x] make a tag and push it to github
    ```
    git tag 6.0.0rc2
    git push --tags
    ```
- [x] go to [GitHub Release](https://github.com/GenericMappingTools/gmt/releases) and make a release. Remember to attach the source tarballs, macOS bundle and Windows installers.
- [x] upload source tarballs, macOS bundle, Windows installers to the GMT FTP (@PaulWessel)
- [x] update README and VERSION files on the GMT FTP
- [x] make announcements

**After release**:

- [x] create branch 6.x for bug-fixes if this is a minor release (i.e. create branch 6.1 after 6.1.0 is released)
- [x] update `GMT_PACKAGE_VERSION_*` in `cmake/ConfigDefault.cmake`
- [x] comment the `set (GMT_PUBLIC_RELEASE TRUE)` line
- [x] commit changes to GitHub

**3rd-party update**

- [x] update [conda-forge feedstock](https://github.com/conda-forge/gmt-feedstock) (@leouieda, @seisman)
- [x] update [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmt.rb) (@seisman)
- [x] update fink package (@remkos)
- [x] update macports ports

---

- [x] Party :tada: (don't tick before all other checkboxes are ticked!)

**Comment by PaulWessel** [comment]
Tests pass on macOS for me.  Do we wait until overnight for Linux and Windows?

**Comment by seisman** [comment]
I can trigger Linux and Windows tests in #948 so we don't need wait for the scheduled builds.

**Comment by PaulWessel** [comment]
OK, looks like Travis is clogged, #1084 is still not completed its testing...

**Comment by seisman** [comment]
We have one failing test (`mapproject/proj4.s`) on Linux, and 35 failing tests on Windows. It looks OK to me.

**Comment by PaulWessel** [comment]
OK, I checked passing the tests.  There is no changelog yet, and no changes to INSTALL etc.  Unless I am missing something, I think we are good to go and check the rest of those boxes, set the parameters in ConfigDefaults.cmake and then move down to the Release tasks.  Is this OK?

**Comment by seisman** [comment]
@PaulWessel Can you approve #1087?

**Comment by seisman** [comment]
I think it's OK to go now.

**Comment by PaulWessel** [comment]
I have built the tar-balls and the macOS bundle and placed them in ftp://ftp.soest.hawaii.edu/pub/pwessel/release

```
MD5 (gmt-6.0.0rc2-darwin-x86_64.dmg) = bd2ace277c074752645d37bc0330bd13
MD5 (gmt-6.0.0rc2-src.tar.gz) = 50aacf0c3a86dd29b125ead2abfa7bfa
MD5 (gmt-6.0.0rc2-src.tar.xz) = 96141e4a9788bfcd2045273d6e2b9be5
```

@joa-quim, please make windows installers.  Once you do we can check those boxes and tag the release.

**Comment by seisman** [comment]
@PaulWessel Don't have permission to your FTP site.

**Comment by PaulWessel** [comment]
Fixed.  That is hard to remember. My default umask leaves off group and other read.

**Comment by seisman** [comment]
I still can't open ftp://ftp.soest.hawaii.edu/pub/pwessel/release or ftp://ftp.soest.hawaii.edu/pwessel/release, 
but I can access ftp://ftp.soest.hawaii.edu/pwessel/release/gmt-6.0.0rc2-darwin-x86_64.dmg.

**Comment by PaulWessel** [comment]
Sorry, I guess the pub is built in to that URL, so the latter is correct. (the dir is pub/pwessel/releases).

**Comment by PaulWessel** [comment]
Should there be a checkbox "Commit changes to GitHub" as the last entry under "After Release"?

**Comment by seisman** [comment]
> Should there be a checkbox "Commit changes to GitHub" as the last entry under "After Release"?

Yes. And also "create branch 6.x if this is a minor release (i.e. create branch 6.1 after 6.1.0 is released)".

**Comment by seisman** [comment]
Tested the macOS bundle and source tarballs on macOS and Linux. They all work well.

**Comment by PaulWessel** [comment]
Thanks, saves me the trouble!

**Comment by joa-quim** [comment]
OK, I've put the Win installers in the Box (@seisman, I sent you a share).
There is, however, a little glitch. cpack now drops the ``win64`` (and ``win32``) parts from the installer name. Had to add them manually.

**Comment by seisman** [comment]
> OK, I've put the Win installers in the Box (@seisman, I sent you a share).

Thanks. I'll test them later.

> There is, however, a little glitch. cpack now drops the `win64` (and `win32`) parts from the installer name. Had to add them manually.

Seems something wrong with #1078. What's the cmake version you're using?

**Comment by joa-quim** [comment]
cmake version 3.14.0

**Comment by seisman** [comment]
Both Windows installers work for me.

**Comment by PaulWessel** [comment]
I am about to place the new tars, bundles, and installers on the ftp and on the Wiki download.  Since these are temporary releases I assume I shall remove all rc1 files.  @seisman, can you put files on the GitHub Release page?  I created teh rc2 tag and pushed it.  All files are in my ftp release directory right now.

**Comment by seisman** [comment]
OK. I'll do it.

**Comment by joa-quim** [comment]
I still can't open ftp://ftp.soest.hawaii.edu/pub/pwessel/release
To download the tarball I had to compose its full address

**Comment by PaulWessel** [comment]
remove the "pub" part.

**Comment by joa-quim** [comment]
There is nothing there (that I am allowed to see)

**Comment by PaulWessel** [comment]
If you just used the directory, that is true, but all files have the right permissions.  I just changed the permissions on the release directory as well to be readable.

**Comment by joa-quim** [comment]
Now (and right now) the show up.

**Comment by seisman** [comment]
The conda-forge package was updated, and the homebrew formula also work well. And no fink and macports. 

All done.
