### ISSUE TITLE
gmt begin map eps outputs both eps and ps files

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#1377]
```
gmt begin map eps
gmt basemap -R0/1/0/1 -JX10c -Baf
gmt end
```
Issues:

1. The script should generate only a EPS file, but actually it generates a EPS and a PS.
2. The EPS file is not correctly cropped at the right and top sides
3. The PS file cannot be opened by Apple Preview, but can be converted to PDF correctly by psconvert.

**Comment by joa-quim** [comment]
Fixed by #1379

**Comment by meghanrjones** [comment]
I still encounter the second problem reported in this issue ("The EPS file is not correctly cropped at the right and top sides") using the master branch. [The note on postscripts in the begin docs](https://docs.generic-mapping-tools.org/dev/begin.html#note-on-postscript) implies that the figure should be cropped for eps output. Is this a bug or documentation issue?

**Comment by PaulWessel** [comment]
I just ran that command and do not notice anything amiss regarding clipping.  What am I missing?  Might you have a gmt.conf laying around in that directory?

**Comment by meghanrjones** [comment]
> I just ran that command and do not notice anything amiss regarding clipping. What am I missing? Might you have a gmt.conf laying around in that directory?

Trying multiple ways to avoid gmt.conf problems:
```
rm gmt.conf
rm gmt.history

gmt clear sessions
gmt --version

gmt begin map eps -C
    gmt basemap -R0/1/0/1 -JX10c -Baf
gmt end show
```
6.3.0_7dac306-dirty_2021.07.25

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/14077947/127052634-93d12934-4be1-49f9-ba84-ac39e0056187.png">

**Comment by PaulWessel** [comment]
If I use Preview "open" then I get that but if I use a PostScript viewer like **gv** it looks correct, and furthermore the first 3 lines in map.eps are correct.

```
%!PS-Adobe-3.0
%%BoundingBox: 0 0 308 300
%%HiResBoundingBox: 0 0 307.6740 299.7000
```

I would chalk that up to Preview being dumb.

**Comment by meghanrjones** [comment]
> If I use Preview "open" then I get that but if I use a PostScript viewer like **gv** it looks correct, and furthermore the first 3 lines in map.eps are correct.
> 
> ```
> %!PS-Adobe-3.0
> %%BoundingBox: 0 0 308 300
> %%HiResBoundingBox: 0 0 307.6740 299.7000
> ```
> 
> I would chalk that up to Preview being dumb.

OK
