### ISSUE TITLE
Incorrect cropping if the origin of second panel is >12 cm below the first panel

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/gmt#195]
**Description of the problem**

**Full script that generated the error**

```
gmt begin map jpg
gmt basemap -JX10c/10c -R0/10/0/5 -Baf
gmt basemap -JX10c/10c -R0/10/0/5 -Baf -Y-13c
gmt end
```

**Output Figure**
![map](https://user-images.githubusercontent.com/3974108/49330616-fcb12980-f55e-11e8-9995-715d814e1dce.jpg)

**System information**

* Operating system: macOS
* Version of GMT: 6.0.0_15a9160

**Comment by PaulWessel** [comment]
In modern mode we basically have an enormous canvas that we clip to the final size.  However, if you purposefully move the origin way to the left or down then this will happen.  Perhaps we should position the origin at (1 meter, 1 meter) to handle relative innocent shifts like this from still working.

**Comment by seisman** [comment]
Yeah. I think most people like to plot the top left panel first. 1 meter seems enough for most plots.

**Comment by PaulWessel** [comment]
We were using GMT_PAPER_MARGIN ( = 5 inches) for this or ~12.7 cm as you found.  I am setting it to 40 inches (a bit over 1 meter) and will submit PR once make check returns without any side-effects.

**Comment by joa-quim** [comment]
Well, we have a 100 m wall don't we? So 1 m may not be that much for people that like to start from top down (but I surely prefer an Y axis positive up).

**Comment by PaulWessel** [comment]
It is 11.55 meters. (32767 points)

**Comment by PaulWessel** [comment]
Bug has now been fixed in ghostscript repository so we are awaiting the 9.27 release before we can close this issue.

**Comment by meghanrjones** [comment]
Just an update that I still get the same incorrect cropping with gs 9.55.0.

**Comment by PaulWessel** [comment]
And I see GMT_PAPER_MARGIN is still 5 in 6.3.0.  Not sure what happen here - the above says we changed to 1 m.  I will again set to 1 m (~40 inches) and we can run tests etc.  Unclear to me why this did not stick.  I agree setting aside a full meter is fine given the canvas is 11 m.

**Comment by meghanrjones** [comment]
> And I see GMT_PAPER_MARGIN is still 5 in 6.3.0. Not sure what happen here - the above says we changed to 1 m. I will again set to 1 m (~40 inches) and we can run tests etc. Unclear to me why this did not stick. I agree setting aside a full meter is fine given the canvas is 11 m.

The increase was reverted in https://github.com/GenericMappingTools/gmt/pull/229 due to a different gs bug discussed in https://github.com/GenericMappingTools/gmt/issues/199. I'll try out the latest PR to see if it's still a problem.
