### ISSUE TITLE
gmt convert crashes if FORMAT_GEO_OUT is blank

### ISSUE THREAD

**Issue by anbj** [GenericMappingTools/gmt#3620]
Obscure stuff, but still. If you forget to tell GMT what template to use you get a crash:

```
$ echo 2.79334970 79.16202276 | gmt convert --FORMAT_GEO_OUT=
ERROR: Caught signal number 11 (Segmentation fault) at
/usr/local/lib/libgmt.so.6(+0xa2e20)[0x7f2da1431e20]
/lib/x86_64-linux-gnu/libnssutil3.so(+0x2a000)[0x7f2d9a3ec000]
Stack backtrace:
/usr/local/lib/libgmt.so.6(sig_handler+0x2ab)[0x7f2da13c89ab]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f2da136a3c0]
/usr/local/lib/libgmt.so.6(+0xa2e20)[0x7f2da1431e20]
/usr/local/lib/libgmt.so.6(gmtlib_geo_C_format+0x43)[0x7f2da143c183]
/usr/local/lib/libgmt.so.6(gmtlib_setparameter+0x187d)[0x7f2da14eb00d]
/usr/local/lib/libgmt.so.6(gmt_parse_common_options+0xc05)[0x7f2da1502955]
/usr/local/lib/libgmt.so.6(GMT_Parse_Common+0x542)[0x7f2da14c8dc2]
/usr/local/lib/libgmt.so.6(GMT_gmtconvert+0x17a)[0x7f2da15ab7ea]
/usr/local/lib/libgmt.so.6(GMT_Call_Module+0x3d5)[0x7f2da13e6295]
/usr/local/lib/libgmt.so.6(GMT_Call_Module+0x634)[0x7f2da13e64f4]
gmt(main+0xb84)[0x564033d6cee4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f2da118a0b3]
gmt(_start+0x2e)[0x564033d6d60e]
```

Using bleeding edge master.

**Comment by anbj** [comment]
(Tell me if I should open new issues about this)

Notice template (*+D: Output longitude in the range [0,360]*). Should not this give ``362.7933497 79.16202276``?
```
$ echo -2.79334970 79.16202276 | gmt convert --FORMAT_GEO_OUT=+D
-2.7933497	79.16202276
```

And similarly for *-D: Output longitude in the range [-360,0]*;

```
$ echo 2.79334970 79.16202276 | gmt convert --FORMAT_GEO_OUT=-D
2.7933497	79.16202276
```

**Comment by anbj** [comment]
Nevermind the post above - forgot to add ``-fg``.

**Comment by joa-quim** [comment]
If it crashes, it's a bug.

**Comment by PaulWessel** [comment]
Fixed by #3624.

**Comment by anbj** [comment]
Just playing around; ``--FORMAT_GEO_MAP= `` still crashes (why would you ever give that to ``gmt convert``..)

```
$ echo 2.79334970 79.16202276 | gmt convert --FORMAT_GEO_MAP=
ERROR: Caught signal number 11 (Segmentation fault) at
/usr/local/lib/libgmt.so.6(+0xa2e20)[0x7f54d63c6e20]
/lib/x86_64-linux-gnu/libnssutil3.so(+0x2a000)[0x7f54cf381000]
Stack backtrace:
/usr/local/lib/libgmt.so.6(sig_handler+0x2ab)[0x7f54d635d9ab]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f54d62ff3c0]
/usr/local/lib/libgmt.so.6(+0xa2e20)[0x7f54d63c6e20]
/usr/local/lib/libgmt.so.6(gmtlib_plot_C_format+0xc5)[0x7f54d63d14e5]
/usr/local/lib/libgmt.so.6(gmtlib_setparameter+0x1760)[0x7f54d647fee0]
/usr/local/lib/libgmt.so.6(gmt_parse_common_options+0xc05)[0x7f54d6497a85]
/usr/local/lib/libgmt.so.6(GMT_Parse_Common+0x542)[0x7f54d645ddb2]
/usr/local/lib/libgmt.so.6(GMT_gmtconvert+0x17a)[0x7f54d654092a]
/usr/local/lib/libgmt.so.6(GMT_Call_Module+0x3d5)[0x7f54d637b295]
/usr/local/lib/libgmt.so.6(GMT_Call_Module+0x634)[0x7f54d637b4f4]
gmt(main+0xb84)[0x55ef8a608ee4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f54d611f0b3]
gmt(_start+0x2e)[0x55ef8a60960e]
```
