### ISSUE TITLE
@remote p instead of g

### ISSUE THREAD

**Issue by joa-quim** [GenericMappingTools/gmt#7859]
```
julia> grdimage("@earth_relief_20m", proj=:Winkel, colorbar=true, coast=true, show=true)
grdimage [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

grdimage [NOTICE]: SRTM15 Earth Relief v2.5.5 at 20x20 arc minutes reduced by Gaussian Cartesian filtering (37.1 km fullwidth) [Tozer et al., 2019].
grdimage [NOTICE]:   -> Download grid file [831K]: earth_relief_20m_p.grd
pscoast [NOTICE]: SRTM15 Earth Relief v2.5.5 at 20x20 arc minutes reduced by Gaussian Cartesian filtering (37.1 km fullwidth) [Tozer et al., 2019].
pscoast [NOTICE]:   -> Download grid file [833K]: earth_relief_20m_g.grd
pscoast [ERROR]: Libcurl Error: HTTP response code said error
pscoast [ERROR]: Probably means @earth_relief_20m.grd does not exist on the remote server
pscoast [ERROR]: Unable to obtain remote file @earth_relief_20m.grd
pscoast [NOTICE]:   -> Download grid file [833K]: earth_relief_20m_g.grd
pscoast [ERROR]: Libcurl Error: HTTP response code said error
pscoast [ERROR]: Probably means @earth_relief_20m.grd does not exist on the remote server
pscoast [ERROR]: Unable to obtain remote file @earth_relief_20m.grd
pscoast [ERROR]: Could not decode @earth_relief_20m.grd, return NaN.
pscoast [ERROR]: Option -R parsing failure. Correct syntax:

  -R<west>/<east>/<south>/<north>[+r]
     Specify the min/max coordinates of your data region in user units. Use dd:mm[:ss] for regions given in arc degrees, minutes
     [and seconds]. Use -R<xmin>/<xmax>/<ymin>/<ymax>[+u<unit>] for regions given in projected coordinates, with <unit> selected
     from e|f|k|M|n|u [Default: e]. If +u is set, projected regions centered on (0,0) may be set via -R<halfwidth>[/⏎
     …<halfheight>]+u<unit>, where <halfheight> defaults to <halfwidth> if not given. Use [yyyy[-mm[-dd]]]T[hh[:mm[:ss[.xxx]]]]
     format for time axes. Append +r if -R specifies the coordinates of the lower left and upper right corners of a rectangular
     area.
     Alternatively, use -R<code><x0>/<y0>/<n_columns>/<n_rows> for origin and grid dimensions, where <code> is a 2-char combo
     from [T|M|B][L|C|R] (top/middle/bottom/left/center/right) and grid spacing must be specified via -I<dx>[/<dy>] (also see
     -r).
pscoast [ERROR]: Offending option -R@earth_relief_20m.grd
ERROR: Something went wrong when calling the module. GMT error number = 72
```

But what it downloads is is the `p` version
``earth_relief_20m_p.grd``

**Comment by PaulWessel** [comment]
Looking now, noting this comment

`if (gmt_remote_dataset_id (GMT->parent, item) != GMT_NOTSET) {	/* Silly, but user set -R@earth_relief_xxy or similar */`

I assume this is Julia blindly adding -Rgridfile to a command that takes a grid, e.g. grdimage grid.grd -Rgrid.grd.  Where do you need this?

**Comment by PaulWessel** [comment]
Being fixed in a few minutes.

**Comment by joa-quim** [comment]
Hmm, don't understand nothing of this. This still fails on Windows but works on WSL
```
C:\v>grdtrack  -G@earth_relief_05m  -R0/20/0/20 -n+a -o3,2 -EBL/TR+d
grdtrack [ERROR]: Libcurl Error: HTTP response code said error
grdtrack [ERROR]: Probably means @earth_relief_05m does not exist on the remote server
grdtrack [ERROR]: Unable to obtain remote file @earth_relief_05m
grdtrack [ERROR]: Must specify -G at least once
```
and it's not a libcurl problem because I was able to do
```
C:\v>gmtwhich @earth_relief_05m_g -Ga
gmtwhich [NOTICE]: Remote data courtesy of GMT data server oceania [http://oceania.generic-mapping-tools.org]

gmtwhich [NOTICE]: SRTM15 Earth Relief v2.5.5 at 05x05 arc minutes reduced by Gaussian Cartesian filtering (9.3 km fullwidth) [Tozer et al., 2019].
gmtwhich [NOTICE]:   -> Download 180x180 degree grid tile (earth_relief_05m_g): S90W180
C:/Users/j/.gmt/server/earth/earth_relief/earth_relief_05m_g/S90W180.earth_relief_05m_g.nc
C:/Users/j/.gmt/server/earth/earth_relief/earth_relief_05m_g/S90E000.earth_relief_05m_g.nc
```

**Comment by PaulWessel** [comment]
Sorry, starting a zoom with Roger - maybe later tonight

**Comment by joa-quim** [comment]
Debugging shows that it is trying to access
```
http://oceania.generic-mapping-tools.org/cache/earth_relief_05m_g
```
That does not exist.

**Comment by joa-quim** [comment]
And locally it's looking for the file in ``C:/Users/j/.gmt/cache/earth_relief_05m_g`` but it should be looking into ``C:\Users\j\.gmt\server\earth\earth_relief\earth_relief_05m_p``

**Comment by PaulWessel** [comment]
Thanks, will check that out.
